### ISSUE TITLE
oid.csv in CCDA-data

### ISSUE THREAD

**Issue by chrisroederucdenver** [cladteam/CCDA_OMOP_by_Python#101]
I see the addition of the third column so we have oid, codeSystemName and vocabulary_id, but not all rows have the third column.

**Comment by AdamLeeIT** [comment]
Yes, those would either need to be mapped from JHU or left without vocabulary. It's possible that OIDs could clutter the file if we don't need them. We might consider discussing OID-only snooping or creating an OID dictionary file, as OIDs for root elements differ from those for code systems, and the information required for each is different. For instance, knowing that root '2.16.840.1.113883.10.20.22.2.5.1' is for the problem section and codeSystem '2.16.840.1.113883.6.1' is for LOINC could be useful for data quality purposes as well.

**Comment by chrisroederucdenver** [comment]
Lots to unpack there.

First and foremost, if it's a three-column table, have two commas and three columns, even if a value is null for each row.

I was using this file to map from OID to OMOP vocabulary id, so I wouldn't think OIDs clutter anything. ...that is that in my mind, this *IS* an OID dictionary: from OID to OMOP vocabulary id. If you mean, to have a separate file for OID to CodeSystemName, that idea makes more sense, but I don't see a a problem with null values in that case.

It really took me a while to see that you had added section template OIDs to what I see as part of the vocabulary mapping process. 

I agree that OIDs play a role in templates, and knowing what they are will be useful. I think they should be kept separate, so I would criticize, not the data format or columns here, but the name and lack of a stated purpose. It should be called the oid_vocabulary_map.csv and exclude OIDs used (exclusively) as root values.

**Comment by AdamLeeIT** [comment]
I concur with the clarifying statement of " If you mean, to have a separate file for OID to CodeSystemName, that idea makes more sense, but I don't see a a problem with null values in that case." which should become the output. My original line of thought was an all encompassing OID dictionary, but that has less benefit than 2 separate files, one for OIDs that are pertinent to the structure of a C-CDA document e.g. root elements and template ids, and one for codeSystems. I like your recommended name of 'oid_vocabulary_map.csv' and going to steal that. 

I can restore the previous OID.csv file if necessary, or you can change it to what is needed.

**Comment by chrisroederucdenver** [comment]
there's something to be said for one OID file, but it needs to be communicated clearly. A PR is an avenue for that, and I believe I've locked commits down on all three respositories to require that....and that includes me which is why you have  PR review assigned.

OK, so considering a single OID file, sorry for any whiplash, .....would leaving out the second column not break anything?
What code should we be running to make sure the extra column doesnt' break anything.

See also https://github.com/cladteam/CCDA_OMOP_by_Python/issues/99
...that's a task we should work through together and something to think about until we can meet.
Look at the output here: https://github.com/cladteam/CCDA_OMOP_by_Python/actions/runs/10857633723/job/30134367556

**Comment by chrisroederucdenver** [comment]
closed with 1f259a4b05c8c3253110f4c3f0a06a2d3a753242 over in CCDA-data
