### ISSUE TITLE
More Mappings: Location

### ISSUE THREAD

**Issue by chrisroederucdenver** [cladteam/CCDA_OMOP_by_Python#105]
On one level, this is pretty easy, but  these can come from many different sources. So this will involve more than configuration each with a different root path into different places we find them. These may be in the encounters and the provider references within them. See also Care Site. #139 and the way the PK is created here, and the matching FK there.

Locations come from participants and well as the patientRole.

**Comment by richard1933** [comment]
According to [OMOP CDM 5.3 ddl](https://github.com/OHDSI/CommonDataModel/blob/main/inst/ddl/5.3/sql_server/OMOPCDM_sql_server_5.3_ddl.sql), the only domain that captures address details (such as city and state) is `person`. The `care_site` and `provider` tables do not include this information.

**Comment by chrisroederucdenver** [comment]
so does care_site.


`CREATE TABLE @cdmDatabaseSchema.care_site (
			care_site_id integer NOT NULL,
			care_site_name varchar(255) NULL,
			place_of_service_concept_id integer NULL,
			location_id integer NULL,...`

**Comment by chrisroederucdenver** [comment]
Thanks for  you help Monique and @richard1933
