### ISSUE TITLE
Checking current crosswalk tables to find missing vocabularies causing 'no matching concept'

### ISSUE THREAD

**Issue by tannerzhang** [cladteam/CCDA_OMOP_by_Python#120]
Current xwalk table : https://foundry.cladplatform.org/workspace/data-integration/dataset/preview/ri.foundry.main.dataset.79e9fddb-03d9-4331-b7fa-cb255cd1c549/master

Filter on target concept id = 0

**Comment by tannerzhang** [comment]
There are ICD-9 codes currently in the snooper file results.

Per @chrisroederucdenver it's a translation code:

_**#<value code="396275006" codeSystem="2.16.840.1.113883.6.96" codeSystemName="SNOMED CT" displayName="Osteoarthritis" xsi:type="CD" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
                    <translation code="715.90" codeSystem="2.16.840.1.113883.6.103" codeSystemName="ICD-9CM" displayName="Osteoarthritis"/>
                    <translation code="M19.90" codeSystem="2.16.840.1.113883.6.90" codeSystemName="ICD-10-CM" displayName="Osteoarthritis"/>
                  </value>
[10:26](https://cladteam-workspace.slack.com/archives/C07N1RPQZRA/p1728483973309499)
...and can probably be ignored.**_ 

Note here for future discussion on ICD-9-CM codes mapping. This will decide whether we download ICD9 related vocabularies and add them to our routinely updated vocabularies. And the information for the vocabs should be kept in the mapping sheet, if we later decide to include them.

**Comment by tannerzhang** [comment]
CPT 4 vocab is missing from the enclave, not fixed yet as of today.

**Comment by tannerzhang** [comment]
The value set responsible party is now missing. ValueSet: ResponsibleParty.
Here is the page for it: https://build.fhir.org/ig/HL7/UTG/ValueSet-v3-ResponsibleParty.html
Note here if we need this for real sample data later.

**Comment by chrisroederucdenver** [comment]
I'm not aware of a use-case for that field. Is it something you track on the vocab end?
...or do you mean it's missing for one specific value set or vocabulary, ICD9?

**Comment by chrisroederucdenver** [comment]
see #39

**Comment by tannerzhang** [comment]
https://foundry.cladplatform.org/workspace/data-integration/code/repos/ri.stemma.main.repository.7866d7b4-44e0-436e-90ec-3508a74d3b6d/pulls/ri.pull-request.main.pull-request.185bba60-e043-41b7-97dd-71111ca1cea0/overview New PR created for review @stephanieshong @chrisroederucdenver

**Comment by tannerzhang** [comment]
A report to check our currently not-mapped codes: https://foundry.cladplatform.org/workspace/contour-app/table/ri.contour.main.analysis.1c57ee78-9301-4f1a-9324-0ea2f5388520/ref/ri.contour.main.ref.44aca91c-510d-49b7-ad99-d70e68115c29/node/6831458b-d12e-3ae9-abf3-7a1c41c56dbc?viewMode=edit

Most of the codes are not mappable -- either they do not have mappings in Athena tables, or we do not have enough information from the codes to map them.

One extra note: For one of the gender codes, in the code system OID, they put in the oid for the valueset (instead of our wanted code system oid), how should we deal with this?

**Comment by tannerzhang** [comment]
https://foundry.cladplatform.org/workspace/fusion/spreadsheet/ri.fusion.main.document.7cb7b84a-ddd9-410c-bf13-6705849945f2/spreadsheet/9629076653913728
Value set mapping table (AKA the static part of the mapping, AKA the more manual part) is updated to include the unit of measures, and to include the correct code systems for the administrative gender and race and ethnicity, another administrative gender code's mapping is added "undifferenciated"

**Comment by chrisroederucdenver** [comment]
I saw your comment at the very top "filter on concept_id = 0" so very useful, thank you.
I looked at source_concept_id =0 and filtered out source_concept_code null and boom, empty table. nice!
Same filter on source_concept_code not null, look for target_concept_id and there are only 7. This is a nice place to be.

Do you think these are old concepts that are from old releases? Or do they not map easily to a standard concept? It could be these are here because the sample documents are old?

```
70618 | 70618 | 2.16.840.1.113883.6.88 | RxNorm | 70618 | 19126544 | Penicillin | RxNorm
-- | -- | -- | -- | -- | -- | -- | --
416949008 | 416949008 | 2.16.840.1.113883.6.96 | SNOMED | 416949008 | 4220304 | Abdomen and pelvis | SNOMED
412307009 | 412307009 | 2.16.840.1.113883.6.96 | SNOMED | 412307009 | 4259208 | Drug vehicle | SNOMED
95971004 | 95971004 | 2.16.840.1.113883.6.96 | SNOMED | 95971004 | 4320959 | Urea nitrogen | SNOMED
87405001 | 87405001 | 2.16.840.1.113883.6.96 | SNOMED | 87405001 | 4337514 | Cane | SNOMED
410942007 | 410942007 | 2.16.840.1.113883.6.96 | SNOMED | 410942007 | 4254051 | Drug or medicament | SNOMED
59058001 | 59058001 | 2.16.840.1.113883.6.96 | SNOMED | 59058001 | 4239796 | General physician | SNOMED
```

**Comment by chrisroederucdenver** [comment]
Closed per @tannerzhang
