### ISSUE TITLE
DQ: CCDA visualization for Other Counts

### ISSUE THREAD

**Issue by chrisroederucdenver** [cladteam/CCDA_OMOP_by_Python#135]
This is the visualization for the CCDA "other" counts

- [x] histogram of measurements per person
- [x] histogram of observations per person
- [x] histogram of diagnoses per person
  - [x] count of persons with 0

Depends on #134 for data.

Detail here for measurements and observations as domain rows counts 108, and 109 where percentages are called for.
Diagnoses are on line 9 where percentages are also called for. 
https://docs.google.com/spreadsheets/d/19cs4hTpLw9maU8UuSIcaj_0JSfcqSKcLQ6ESHy5_yFo/edit?gid=319835440#gid=319835440

**Comment by chrisroederucdenver** [comment]
Delayed because of data dependency.
Great review of progress on 11/21. We discussed and clarified our plan for CCDA a bit. The table breaks out by name and code. In the case of "No matching concept" we get more than one code with that name and the visualization tool conveniently breaks the row into two colors showing that. We decided that with a comparison of OMOP and CCDA in mind, we'd map concepts to OMOP and leave the rest as pure CCDA as possible.  Just a warning here, we may get contrary opinions out of the DQ group and have to make changes.

**Comment by chrisroederucdenver** [comment]
@JCavallJH I added viridis colors to most of the graphs. I went with 12 colors and 32 letters.
I don't know if repeating is bad for ones where we go to 32. 
I also added a few "limit 32" to queries.
https://waldyrious.net/viridis-palette-generator/

**Comment by tursynay** [comment]
@JCavallJH , pinging for updates.

**Comment by JCavallJH** [comment]
@tursynay Sorry about the delay. Task has been completed.

**Comment by chrisroederucdenver** [comment]
Looks nice!
![Screenshot 2024-12-20 at 9 42 01 AM](https://github.com/user-attachments/assets/5bff1c36-8fa7-4906-90dc-658d26a198f9)
