### ISSUE TITLE
More Mappings: Provider

### ISSUE THREAD

**Issue by chrisroederucdenver** [cladteam/CCDA_OMOP_by_Python#140]
As with care sites #139 we will find providers in many document locations, link them with care_sites using a method similar to the way care-sites are linked to locations. 

## Deliverables
Let's make the "ask" clear. Each of you, mostly independently, should have
- [x]  a configuration written for the provider fields provider_id, name, npi, specialty_concept_id, care_site_id. 
  - This will involve a DERIVED field for the specialty_concept_id,
  -  a HASH for the ID (possibly from the root and extension attributes if the provider has an id element)
  - The rest are FIELDs.

#173 is for location and care_site
#154 is for linking providers and encounters

Do this work in a branch if you can. Since you should be creating new files, there's no chance of over-lapping or conflicting with someone else, so master is OK.

As you complete each bullet, I'd like you to run it in the Workspace
-  get into the workspace, select your branch
-  start a terminal, run the bin/process.sh program
-  have a look at the files in output that are named after the input file and the outer-most level name in the configuration

@JCavallJH and @AdamLeeIT  have seen this process and should be able to help.
Minimum is getting the base provider config together and running.

## Tips
Parts of this are hard, and just seeing the questions is great progress:
- The OMOP CDM has providers in many different places. Do we fill in the same one in each place? If different, how and why, and where in CCDA do they come from? Some of these may be answered with a more careful read of the OHDSI doc.s
  - person
  - visit_occurrence (most important, maybe most clear)
  - measurement and observation tables
  - drug_exposure
  - condition_occurrence

## Reference
[Config Docs "Metadata.py" ](https://docs.google.com/document/d/1mLk1GU53MH3GuFcFYBHFqa1LthnTZVw441noCZoyuq4/edit?tab=t.0#heading=h.ehx2r82nyjqf)

[OHDSI OMOP 5.4 CDM pages ](https://ohdsi.github.io/CommonDataModel/cdm53.html)

Many clues to how ID linking works is in the [Encounter Analysis](https://docs.google.com/document/d/1gp1mI83Ee2A3z3a6YxaVMUTKcXIKe6buCxGZMelN3_g/edit?tab=t.0#heading=h.wsfwvw3bcjw7)

## OMOP Provider Table reference
CREATE TABLE @cdmDatabaseSchema.provider (
            provider_id integer NOT NULL,
            provider_name varchar(255) NULL,
            npi varchar(20) NULL,
            dea varchar(20) NULL,
            specialty_concept_id integer NULL, 
            care_site_id integer NULL,
            year_of_birth integer NULL,
            gender_concept_id integer NULL,
            provider_source_value varchar(50) NULL,
            specialty_source_value varchar(50) NULL,
            specialty_source_concept_id integer NULL,
            gender_source_value varchar(50) NULL,
            gender_source_concept_id integer NULL );

**Comment by richard1933** [comment]
there are two places for provider information from 'CCD-Sample.xml', one is documentationOf/serviceEvent/performer 
another one is in html table (not so obvious and not reliable?!) component/structuredBody/section/text->table/tbody/tr/td
@todo: need to have care site table first (depend on the care_site_id)
@todo: need also to map specialty_concept_id

**Comment by chrisroederucdenver** [comment]
@richard1933  Care site is committed. There are two configurations because we found it in (at least) two places.
care_site_ee_hcf.py is from encompassingEncounter HealthCareFacility
care_site_pr is from Encounter participantRole (should be renamed care_site_e_pr).

Regarding concepts, at least those used in the test documents should have a mapping to a standard concept in one of the two mapping tables.
https://foundry.cladplatform.org/workspace/data-integration/dataset/preview/ri.foundry.main.dataset.5ba1594c-ef36-4eeb-b6c4-d3d005dbd127/master
https://foundry.cladplatform.org/workspace/data-integration/dataset/preview/ri.foundry.main.dataset.28fe6af8-0b22-4b45-86e2-b394c62dcd09/master

Greater detail about the mappings in the HL7 doc.s https://www.hl7.org/ccdasearch/index.html
(section/text is html and we will not use it, but there may be a parallel entry at component/structuredBody/section/entry...)
For the first one, this page starts with some detaile https://www.hl7.org/ccdasearch/templates/2.16.840.1.113883.10.20.22.1.1.html
But you probably wnat to dig deeper into assignedEntity for a code from the HealthCare Provider Taxonomy 2.16.840.1.114222.4.11.1066 ?
https://vsac.nlm.nih.gov/valueset/2.16.840.1.114222.4.11.1066/expansion/Latest

[HealthcareProviderTaxonomy.xlsx](https://github.com/user-attachments/files/17909575/HealthcareProviderTaxonomy.xlsx)

**Comment by chrisroederucdenver** [comment]
Looking at doc.s @richard1933 @mbangudi  please double check. (filenames abbreviated)
- 170 has a NUCC "207R00000X"
....and I recognize it, and know there are about 10 of these codes in the mapping tables from @tannerzhang .

So @tannerzhang , if  it helps, the value set from VSAC is mentioned and attached (the xlsc file) above.

**Comment by richard1933** [comment]
@chrisroederucdenver  would you be able to see table https://foundry.cladplatform.org/workspace/data-integration/dataset/preview/ri.foundry.main.dataset.223d2426-465c-4e38-b21d-f711c7ad6e00/master ?
vsac_HealthcareProviderTaxonomy contains 851 but, OMOP concept has only 667 NUCC

**Comment by chrisroederucdenver** [comment]
Not closed today b/c we are only getting output from the file that starts with "170". Need to review the xml files we have and verify we should not be getting data from the others, or figure out what's wrong.

**Comment by chrisroederucdenver** [comment]
@mbangudi @richard1933 
Richard and I found what I think will solve this. We had the template ID for the section in the provider.py pointed to Care Plan, not Encounter. We changed it from ...20.22.2.10 to ...20.22.2.22.1 and we get rows for a bunch more files.
(I'm in the middle of making sure the commit went right, but that OID change is in the ROOT element at the top.)

We found it by comparing the paths we had with what it found in the 170 document. Scrolled up to see the top of the section and noticed the comments about Care Plan not Encounter.

**Comment by chrisroederucdenver** [comment]
Closing this on to mark completion of the basics of one path for Provider info.
Work is continuing as we find other places to harvest provider information while working on care_site, related locations and linking them together. 
See the task list in  a comment at the bottom of #151
