### ISSUE TITLE
Additional vocabularies for Race etc. 

### ISSUE THREAD

**Issue by chrisroederucdenver** [cladteam/CCDA_OMOP_by_Python#147]
As discussed in e-mail, we need additional vocabularies. I think we have ....5.104, and we need ....6.238.
I also think HL00005 is an alias for ....6.238.  These are all vocabularies that show up with the conccept 2106-3. i'm creating this ticket so I can close out the related on about using the JHU tables, which has been completed.

Are there other vocabularies that came up in the e-mail?

(editted out mention of VSAC for these, I think that's wrong)

2106-3,2.16.840.1.113883.6.238

2106-3, CDCREC

2106-3,HL70005

2106-3,MX-CODESET-RACE

2106-3,CHPI-RACE

2106-3,2.16.840.1.113883.5.104

**Comment by tannerzhang** [comment]
[https://foundry.cladplatform.org/workspace/fusion/spreadsheet/ri.fusion.main.document.7cb[…]ddd9-410c-bf13-6705849945f2/spreadsheet/9629076653913728](https://foundry.cladplatform.org/workspace/fusion/spreadsheet/ri.fusion.main.document.7cb7b84a-ddd9-410c-bf13-6705849945f2/spreadsheet/9629076653913728)
Row 969 - row 1078 are the newly added rows to include the code system varieties found in Race codes.

I am also considering introducing another step to map all the alias to one code system so this might look cleaner in our valueset mapping table. but open to any group discussion/decision later. But the current table should suffice at least.

It is now synced to the dataset for mapping. @chrisroederucdenver

**Comment by chrisroederucdenver** [comment]
It's only duplication if you know for sure they are the same vocabulary. I appreciate the concern for duplication. It's a corner of what 3NF is, but you have to ask if it is really duplication. If there are different organizations adding terms or publishing that content, a method to consolidate them into a single list assumes they will always be the same, and risks creating bugs when our use-case gets broader and includes larger parts of them (though doubtful) or that one organization adds or removes a term and the others don't or only do so after some amount of time.

From a performance or resource point of view, these are small lists and we shouldn't notice a loss of performance.

**Comment by chrisroederucdenver** [comment]
Thanks Tanner!
Something to think about is how to test this work. 
- One is to run the converter.  It's not getting concepts. I need to add functionality so source values have both OID and the code to help debug this...then debug it.
- Another is to write a query that shows that the concepts that would be in the common table we  decided against are in each vocabulary. It doesn't show everything, but it does confirm that minimum. I've eyeballed for concepts failing above and they seem to be there. ...6.238, 2106-3

**Comment by chrisroederucdenver** [comment]
Good job.
More detail about this work is under CDCREC in #142 .
