### ISSUE TITLE
Retrieve and Parse the Encounter Code ValueSet from VSAC

### ISSUE THREAD

**Issue by chrisroederucdenver** [cladteam/CCDA_OMOP_by_Python#149]
To help with mapping for visit_concept_id #72 getting values for visit_concept_id, it would be helpful to get the valueset specified in CCDA.

https://vsac.nlm.nih.gov/valueset/2.16.840.1.113883.3.88.12.80.32/expansion/Latest

This involves not just login and permissions from VSAC, but also uploading to the Foundry.

**Comment by richard1933** [comment]
[vsac_EncounterTypeCode.json](https://github.com/user-attachments/files/17742370/vsac_EncounterTypeCode.json)

**Comment by chrisroederucdenver** [comment]
Thanks @richard1933 ! I just sent it as an attachment to Matt Owens who will upload it. That turns out to be the easy way. You were right.

I asked him to put it into CCDA/transforms/mapping-reference-files. FYI @stephanieshong  @tannerzhang

**Comment by chrisroederucdenver** [comment]
OK, uploaded here: https://foundry.cladplatform.org/workspace/data-integration/dataset/preview/ri.foundry.main.dataset.6a83f3d6-4cd6-413b-9db3-9a792118e69f/master

It will need extracting from the dataset and more significantly parsing into a table.

**Comment by AdamLeeIT** [comment]
The source (https://vsac.nlm.nih.gov/valueset/2.16.840.1.113883.3.88.12.80.32/expansion/Latest) has a export resource into a Excel file, rather than parsing the json, I am requesting Palantir to upload the CSV into a dataset instead of the JSON. 
[EncounterTypeCode.csv](https://github.com/user-attachments/files/17834564/EncounterTypeCode.csv)

**Comment by chrisroederucdenver** [comment]
@AdamLeeIT 
 The way we did it with the other file was to download it and e-mail the file to him (at his request).
Also, could you CC me on Slacks or e-mails to Matt?

**Comment by AdamLeeIT** [comment]
@tannerzhang @chrisroederucdenver 
This ticket is now complete. I converted the VASC ValueSet JSON file uploaded by Palantir into a tabular format dataset.

The dataset is named: `vsac_EncounterTypeCode`
It is located here: [/All of Us-cdb223/Identified: HIN - HIE/CCDA/transform/vsac_EncounterTypeCode](https://foundry.cladplatform.org/workspace/compass/view/ri.compass.main.folder.266a68fe-b617-4b6c-b241-e927a9525449 )

The dataset has the following columns: [id, system]

**oid**: This column contains the OID of the value set, extracted from the root `id` element of the JSON. It is the same value for every row and provides a consistent reference to the source of the data. _Its value is always 2.16.840.1.113883.3.88.12.80.32 for this dataset._
**system**: Specifies the system or namespace for the coding scheme (e.g., http://www.ama-assn.org/go/cpt). This was as sourced from the JSON file and _is always http://www.ama-assn.org/go/cpt  for this dataset._
**version**: Indicates the version as sources from the JSON. _It is always 2025 for this dataset_
**code**: The unique CPT code within the system that identifies a specific encounter type or procedure. These codes are often numeric or alphanumeric.
**display**: A human-readable description of the code, explaining the type of encounter or service it represents (e.g., "Observation Care Discharge Services").

The Python for generating this dataset is located In CCDA-Tools WorkSpace.
[](https://genoa-containers.palantirfoundry.com/foundry-container-service/proxy/ri.foundry-container-service.main.container.1164396b-fb8b-415e-9362-baa26a9a9029_master/lab/tree/vsac_encountertypecode.ipynb)

**Comment by richard1933** [comment]
mapped 186 out of 203 CPT4 code to OMOP concepts, dataset is located at https://foundry.cladplatform.org/workspace/data-integration/dataset/preview/ri.foundry.main.dataset.7c182b87-2c2b-4e41-8c9c-1f93e7b463d8/master

**Comment by chrisroederucdenver** [comment]
@AdamLeeIT The link you provided above is to an instance of a VM that isn't running. I get an error when using that link. 
![Screenshot 2024-11-22 at 8 41 48 AM](https://github.com/user-attachments/assets/1fba2543-9ead-4ed0-836b-1e03f9f02d83)

Instead send links to code in code repositories instead like this: https://foundry.cladplatform.org/workspace/data-integration/code/repos/ri.stemma.main.repository.42f809ff-135a-45ce-bc46-683c2ca00426/contents/refs%2Fheads%2Fmaster/vsac_encountertypecode.ipynb

**Comment by chrisroederucdenver** [comment]
@richard1933 this looks like a start at mapping the vsac set above to standard concepts? Am I right??

What we ultimately need is a mapping to concepts for use in the visit_occurrence.visit_concept_id, which I believe is the Visit domain. @mbangudi had expressed interest in that mapping. Please include her. There's a ticket for it #72 

Monique, I'm talking about a query in the workbook Richard linked above: https://foundry.cladplatform.org/workspace/vector/view/ri.vector.main.workbook.03b65dcf-84b4-4d25-ac7e-579b548667f3?table=728a58fb-7751-4cc3-b106-f3c6688760d5&branch=master

**Comment by chrisroederucdenver** [comment]
@AdamLeeIT also for vocabulary things like this I think putting the output in the mapping-reference-files under transforms.
