### ISSUE TITLE
CCDA CCD Ambulatory visit_occurrence

### ISSUE THREAD

**Issue by croeder** [cladteam/CCDA_OMOP_by_Python#15]
care_site_id and provider_id are the same
same for the CCDA CDA InPatient file

**Comment by chrisroederucdenver** [comment]
This is almost a duplicate of #14 . More to the point, it is  a less significant issue than in #14.
This just shows how much those two files are copies of each other. Having a second set of data that happen to have the same care_site and provider_id is a non-issue.
