### ISSUE TITLE
Find or create some XML with observations that would map to the OMOP measurement table

### ISSUE THREAD

**Issue by chrisroederucdenver** [cladteam/CCDA_OMOP_by_Python#41]

**Comment by AdamLeeIT** [comment]
Uploaded [Patient-502.xml](https://github.com/chrisroederucdenver/CCDA-data/blob/main/resources/Patient-502.xml) to test for measurements. 
Unit Test would be 
<component>
<observation classCode="OBS" moodCode="EVN">

<templateId root="2.16.840.1.113883.10.20.22.4.27"/>
<id root="c6f88321-67ad-11db-bd13-0800200c9a66"/>
<code xsi:type="CD" code="39156-5" codeSystem="2.16.840.1.113883.6.1" displayName="BMI" codeSystemName="LOINC"/>
<text>
<reference value="#VitalSign1"/>
</text>
<statusCode code="completed"/>
<effectiveTime value="20090516100000"/>
<value xsi:type="PQ" value="26.4" unit="kg/m2"/>
</observation>
</component>

**Comment by chrisroederucdenver** [comment]
I thought the file starting with C-CDA would cover that.
The code expects documents. Either we can wrap this in as a doc. or adapt the code.

**Comment by chrisroederucdenver** [comment]
See also C-CDA_R2-1_CCD.xml and a modified version C-CDA_R2-1CCD_modified.xml for some domain_id routing.
