### ISSUE TITLE
add per-file domain_id mapping to task matrix

### ISSUE THREAD

**Issue by croeder** [cladteam/CCDA_OMOP_by_Python#51]
CCDA-tools/create_map_to_standard.py creates a map from (oid, concept_code) to concept_id, but includes section.

If we apply the mapping to the files individually, we can see how the domain_id routing breaks out per file and fill in that data to the task matrix, and we can set epectations for the output mapping.

**Comment by chrisroederucdenver** [comment]
Duplicate of #82
