### ISSUE TITLE
Add provenance of new files to CCDA-data/README.md, update test data

### ISSUE THREAD

**Issue by chrisroederucdenver** [cladteam/CCDA_OMOP_by_Python#58]
See updated file for examples on previously received files.

The entire CCDA-data/resources directory is used for tests of the tools in CCDA-tools as well as the parser in CCDA_OMOP_by_Python. Consider running that code, verifying the output and adding it to the tools_correct_output, and correct_output directories as tests may/should fail without something to compare to.

**Comment by chrisroederucdenver** [comment]
@AdamLeeIT Could you modify this file and include where the Patient-502.xml file comes from?
It has a different root for the patientID, and I'd like to be able to track it with other files we may see that use the same.

**Comment by AdamLeeIT** [comment]
Tried a new format for better readability, and the source to Patient-502 is present. Added notes, but not sure if that is going to work well. @chrisroederucdenver thoughts on deleting invalid files? --or-- using invalid files as benchmarks for DQ, like known failures.

**Comment by chrisroederucdenver** [comment]
Bogus files are a part of reality and we should be able to deal with them. The bennis file is a short-term fix so we can make use of the content until we get a filter in place to properly escape files that haven't been escaped.

This will probably be an evolution. Since we have --directory flags on our executables, and tests that check for how well a file is being processed, we should be sure to include benchmark files, the ones in either tools_correct_output or prototype_2/correct_output when we add a new file.

We need to start thinking about a processing report. Invalid files will be useful to test that.
