### ISSUE TITLE
PPRL Linkage Clarification

### ISSUE THREAD

**Issue by chrisroederucdenver** [cladteam/CCDA_OMOP_by_Python#80]
Though the HIE/HIN data won't be included in the DRC or AoU Researcher Workbench, there is interest in DQ that compares data retrieved for participants to data from other sources (AoU EHR). This will require PPRL linkage as for other milestones.

Issue here to confirm and clarify this requirement. 

Is Rob on github?

**Comment by tursynay** [comment]
Yes, Rob is on GitHub, he has not accepted this org invite. @schuffr, please accept :)

**Comment by tursynay** [comment]
Should we add this topic to the OMOP Mapping Leads meeting on Sept 10, @chrisroederucdenver

**Comment by tursynay** [comment]
Added Rob here

**Comment by chrisroederucdenver** [comment]
@tursynay I expect the answer is "yes". I just need a reminder/confirmation. I'm basically confusing the fact HIE data is NOT going all the way to AoU, but must be involved in some linkage to compare to the rest of the CLAD data. 
I will also ask more questions in the DQ meetings where this gets discussed.

- [ ] I think the way you say this with the TLAs is that the HIE data is going to the DLC, but not the DRC. (confirm)

**Comment by chrisroederucdenver** [comment]
As far as formal Datavant PPRL, HIE/HIN data won't be doing that.
field-matching between documents within HIE/HIN is an option without them.
