### ISSUE TITLE
Uber Unique IDs

### ISSUE THREAD

**Issue by chrisroederucdenver** [cladteam/CCDA_OMOP_by_Python#83]
Unique IDs impact us in two ways. 

Inter-document IDs like person_id especially when the same person has data coming through different providers, and duplicates mean we may need a table of person_ids and many attributes from which to hash, likely a table that is not part of OMOP, but close to the person table.

Intra-document IDs like visit_occurrence_id that many domain tables refer to.

The following issues address some of these:

-  #78 consider mapping profiles for different data providers (DEFERRED)
-  #71 Visit IDs
-  #42 Receiving data on same patient...
-  #30 care_site_id and provider_id (in test data are bogus, the term for NPI)
-  #29 multiple person_ids, using a sequence or hash
-  #27 measurement_ids are not unique in test data
-  #40 create a method for creating IDs (closed/complete)
-  #16 Multiple fields, priority (closed/complete)
-  #129 Add source id columns
-  #14 scope domain row IDs to the data responder in case of duplication 

see also: https://docs.google.com/document/d/1dGsC_g9mDZD2s712-Td2teq7W0GAJix_dIPDKgHqKc4/edit?tab=t.0#heading=h.2sx98cy2ao6w

**Comment by chrisroederucdenver** [comment]
Progress: Identify the PKs and their FKs, types

- person: person_id integer, location_id integer/null, provider_id integer/null, care_site_id/null
- visit_occurrence: visit_occurrence_id integer, person_id integer, provider_id integer/null, care_site_id integer/null
- location:
- care_site:
- provider:
- measurement
- observation
- condition_occurrence

**Comment by chrisroederucdenver** [comment]
https://docs.google.com/document/d/1dGsC_g9mDZD2s712-Td2teq7W0GAJix_dIPDKgHqKc4/edit

**Comment by chrisroederucdenver** [comment]
KEEP THIS IN MIND:
you can cover lots of bases, the potential for different root values and different combinations of the presence or lack of root and extension, but you still may have many instances of id elements! It makes repeatability difficult.
Q: does this happen in real life?
Q: should we ditch these keys and use a natural key composed of other fields?

**Comment by tursynay** [comment]
Chris will take a look and see if the items are all should be closed

**Comment by chrisroederucdenver** [comment]
They are not all done.

They were closed as a way to limit the list of bugs and subsume this in the uber/super ticket.
Since they show up as done in too many places in this way, they are being re-opened to accurately and clearly reflect their incomplete state.

**Comment by chrisroederucdenver** [comment]
This ticket has served it's purpose. There are still some open, but don't need grouped like before.
