### ISSUE TITLE
Loosen section_code_snooper.py, or replace with raw_code_snooper.py

### ISSUE THREAD

**Issue by chrisroederucdenver** [cladteam/CCDA_OMOP_by_Python#88]
In CCDA-tools, the section_code_snooper.py included metadata that directs it to certain sections. This list is incomplete, though so are our plans. 

A new script there raw_section_snooper.py doesn't restrict the sections it snoops. It's focus is to find what data is in a document as part of thinking about  how to create a coverage report. But it looks like it may pick up a more comprehensive set of terms, and likely more than we need...but more is better than less.

https://github.com/cladteam/CCDA-tools/blob/main/raw_section_snooper.py

More thinking down the lines of the coverage report involves. possible routes and domain_ids into OMOP!

**Comment by chrisroederucdenver** [comment]
see #82  too.

**Comment by AdamLeeIT** [comment]
Got it and I will prioritize this and #82

**Comment by AdamLeeIT** [comment]
Took a crack at a variant code snooper for "section_code_snoooper for creating files for JHU to do vocabulary with" committed branch 88, for us to review

**Comment by AdamLeeIT** [comment]
This issue has 2 main components. The first being the snooping of the sections for vocabulary to provide to JHU. I think this task was resolved with the vocab_snooper.py and any edits with that deliverable becomes a new issue with vocab_snooper.py recommendations.

The second component was the coverage report. Which leads to the gold standards and other tasks.  The raw_section_snooper.py on Foundry is up and running with need of some love, e.g. using concept.txt for vocabs. but, the raw_section_snooper.py is on its way to be the file for generating the coverage report.

We should possibly archive section_code_snooper.py (it evolved to vocab_snooper.py)
archive section_snooper.py (although I love the arguments for top, section element and detail)
rename raw_section_snooper.py to coverage_snooper.py
Review the rest

**Comment by chrisroederucdenver** [comment]
I noticed a change in vocab_maps.py that may have been related to this issue.

The change adds use of a Dataset function which I haven't see. Can you share what it does and why make the change?
Would the other functions in the file benefit from the same change?

Secondly, if it's a reasonable change, there's no need to comment out the former code, especially with a harder to see block comment. Git will keep the older code.

from the diff:
` 
 def read_concept():
-    concept_df = pd.read_csv("../CCDA_OMOP_Private/CONCEPT.csv",
+    from foundry.transforms import Dataset
+    concept_df = Dataset.get("omop_concept").read_table(format="pandas")
+    """
+    concept_df = pd.read_csv("omop_concept_files",
                              engine='c', header=0, sep='\t',
                              #index_col=0,
                              on_bad_lines='warn',`
