### ISSUE TITLE
Proactive Value Sets (for JHU?)

### ISSUE THREAD

**Issue by chrisroederucdenver** [cladteam/CCDA_OMOP_by_Python#89]
Looking at the HL7 Spec.s I can see value sets used for the codes in different subsections.
It's not clear where to find the contents, or _how useful these are_, but here's a start at a list of them, by (structure type, those names you see in the doc.s or the comments in the XML. They are often the values of component or entry).

- [Results Section](https://www.hl7.org/ccdasearch/templates/2.16.840.1.113883.10.20.22.2.3.1.html)
  - [Results Organizer](https://www.hl7.org/ccdasearch/templates/2.16.840.1.113883.10.20.22.4.1.html)
    - [ResultObservation](https://www.hl7.org/ccdasearch/templates/2.16.840.1.113883.10.20.22.4.2.html)
      - UnitsOfMeasureCaseSensitive value set   [2.16.840.1.113883.1.11.12839 ](https://vsac.nlm.nih.gov/valueset/2.16.840.1.113883.1.11.78/expansion/Latest) 
- [Problem Section](https://www.hl7.org/ccdasearch/templates/2.16.840.1.113883.10.20.22.2.5.1.html)
  - [Problem Concern Act ](https://www.hl7.org/ccdasearch/templates/2.16.840.1.113883.10.20.22.4.3.html)
    - [ProblemObservation](https://www.hl7.org/ccdasearch/templates/2.16.840.1.113883.10.20.22.4.4.html)
      - ProblemType value set  [2.16.840.1.113883.3.88.12.3221.7.2](https://vsac.nlm.nih.gov/valueset/2.16.840.1.113883.3.88.12.3221.7.2/expansion/Latest)
      - Problem value set  [2.16.840.1.113883.3.88.12.3221.7.4](https://vsac.nlm.nih.gov/valueset/2.16.840.1.113883.3.88.12.3221.7.4/expansion/Latest)
- [Health Concerns Section](https://www.hl7.org/ccdasearch/templates/2.16.840.1.113883.10.20.22.2.58.html)
  - [HealthStatusObservation](https://www.hl7.org/ccdasearch/templates/2.16.840.1.113883.10.20.22.4.5.html)
    - HealthStatus value set  [2.16.840.1.113883.1.11.20.12](https://vsac.nlm.nih.gov/valueset/2.16.840.1.113883.1.11.20.12/expansion/Latest)
- [Encounter Section](https://www.hl7.org/ccdasearch/templates/2.16.840.1.113883.10.20.22.2.22.1.html)
  - [EncounterActivity](https://www.hl7.org/ccdasearch/templates/2.16.840.1.113883.10.20.22.4.49.html)
    - EncounterTypeCode value set  [2.16.840.1.113883.3.88.12.80.32](https://vsac.nlm.nih.gov/valueset/2.16.840.1.113883.3.88.12.80.32/expansion/Latest)
- Medications TBD

**Comment by AdamLeeIT** [comment]
@chrisroederucdenver Did you get to peek at the oid_lookup.py in branch 88? I think it will be a fun conversation (like legit fun) 
OID 2.16.840.1.113883.1.11.12839 leads to UCUM and codeSystem 2.16.840.1.113883.6.8, and for contents (parsable) 
viola [https://phinvads.cdc.gov/baseStu3/CodeSystem/2.16.840.1.113883.6.8](https://phinvads.cdc.gov/baseStu3/CodeSystem/2.16.840.1.113883.6.8 )

**Comment by stephanieshong** [comment]
ucum unit mappings should be already present in our valueset mapping table, we can transfer for CCDA use.

**Comment by stephanieshong** [comment]
which encounterType are you using? 
You need to let us know the encounter type data element values you are using or the codeSystem. 
--


</html>
</body>
</html>

**Comment by chrisroederucdenver** [comment]
Adding OIDs to this list is on my ToDo. I'll comment and tag when I do.

This isn't urgent, but was meant as a conversation starter.

**Comment by chrisroederucdenver** [comment]
@stephanieshong  @tannerzhang  Links to HL7 docs and VSAC valueset pages added.

**Comment by stephanieshong** [comment]
@chrisroederucdenver  - There are three different mapping tables we are currently managi7g: 
1.vocabulary id mapping between HL7 and OHDSI ( i.e. OIDS to vocabulary_ids)
2. externally defined and managed terminology codes that OHDSI OMOP CDM harmonize into OMOP concept_ids
3. valueset mapping data element entries that falls out of the externally managed terminology codes and falls somewhere in the area that the source data uses like custom defined terms, or like unit of measure UCUM codes, discharge status codes, race, ethnicity, and gender 

If you are asking something else we should meet and make sure we are on the same page.

**Comment by chrisroederucdenver** [comment]
@stephanieshong this is about #3 valueset mapping, but not an immediate need. Closing for now.

**Comment by stephanieshong** [comment]
ok. Sound good.

**Comment by chrisroederucdenver** [comment]
Re-opening for Tanner's request to list value sets as in this FHIR document.
https://docs.google.com/spreadsheets/d/1mBCswpIahjJMrGAz7dKNaChfGAbbgJDEpOZNT3wCFk4/edit?gid=736610689#gid=736610689

**Comment by chrisroederucdenver** [comment]
@tannerzhang is this work valuable?

**Comment by chrisroederucdenver** [comment]
Closing.
If/when we need to identify value sets used in the CCDA spec and possibly retrieve them from VSAC, we'll do so  with much more carefully specified issues.
