### ISSUE TITLE
Convert from xml.etree.ElementTree to lxml.etree

### ISSUE THREAD

**Issue by chrisroederucdenver** [cladteam/CCDA_OMOP_by_Python#91]
I'm hoping this is no more than changing the import name.
The motivation is the addition of getpath and getelementpath functions useful in snooping.

The way to do this would be to change the import in prototype_2/data_driven_parse, then run and test the layer_datasets.py file.

**Comment by chrisroederucdenver** [comment]
done for the CCDA_OMOP_by_Python (may never have been written with ElementTree)
needs done for CCDA-tools.

**Comment by chrisroederucdenver** [comment]
@AdamLeeIT any news?

**Comment by AdamLeeIT** [comment]
The workspace CCDA-Tools is converted to lxml for all .py files that contained element tree in foundry.
