### ISSUE TITLE
Tracing Info Table

### ISSUE THREAD

**Issue by chrisroederucdenver** [cladteam/CCDA_OMOP_by_Python#94]
Not logs, but a table with an entry for each datum that lists source file and XPath, rule, s/w release and date.

Idea is to reconcile data brought into OMOP with a more simply collected list of available list of files and oaths

**Comment by AdamLeeIT** [comment]
Is this tracing info table different from #82 and the provenance table output from the coverage report?

**Comment by chrisroederucdenver** [comment]
It's input to what creates the coverage report.
Here's a crude attempt at what I'm thinking:
- on the input side, you have a raw snooper that tells you want code/codeSystems are in the data. It might have columns file, path, code, codeSystem, value....date?
- on the OMOP side, you have this table that ties rows we create for OMOP to some tracing data that says where it came from. It might have columns, file, path, code, codeSystem, rule and the ID from the OMOP domain this data went into, like observation_id.

The report is a reconcilliation of the two. One the one hand we match input to OMOP. On the other we identify abandonded input.

**Comment by chrisroederucdenver** [comment]
duplicate of #82
